local Repo = 'https://raw.githubusercontent.com/Jonthedruger/lunar.lol'
local Main = Repo .. '/main/'
local Memory = load(gg.makeRequest(Main .. 'Functions/Memory.lua').content)()
Memory.SetRanges(Memory.CodeApp)

-- yuh ( beta )
Memory.Search(":AnoSDKDelReportData3", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKDelReportData4", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKFree", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKGetReportData3", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKGetReportData4", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKSetUserInfoWithLicense", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)
Memory.Search(":AnoSDKDelReportData", Memory.Byte)
Memory.GetResults()
Memory.Edit("0", Memory.Byte)

Memory.SetRanges(Memory.CodeApp | Memory.Anonymous)
