- name: Generate changelog table
  run: |
    echo "| Version | Changes |" > changelog_table.md
    echo "|---------|---------|" >> changelog_table.md
    awk '/Changelogs/{flag=1;next}/return/{flag=0}flag' Modules/Version.lua \
      | sed -E "s/\['([^']+)'\] = ['\"](.*)['\"],?/\| \1 \| \2 \|/g" >> changelog_table.md
    echo "Generated changelog table:"
    cat changelog_table.md
